#############################################################################
# Makefile for building: SERVER
# Generated by qmake (2.01a) (Qt 4.8.1) on: Thu Aug 21 17:48:15 2014
# Project:  SERVER.pro
# Template: subdirs
# Command: /usr/bin/qmake -o Makefile SERVER.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-SIMS_SERVER \
		sub-PanelCommPluginV1

SIMS_SERVER//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) SIMS_SERVER/ || $(MKDIR) SIMS_SERVER/ 
	cd SIMS_SERVER/ && $(QMAKE) /home/anton/Desktop/SecureT\ Server/SIMS_SERVER/SIMS_SERVER.pro -o $(MAKEFILE)
sub-SIMS_SERVER-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) SIMS_SERVER/ || $(MKDIR) SIMS_SERVER/ 
	cd SIMS_SERVER/ && $(QMAKE) /home/anton/Desktop/SecureT\ Server/SIMS_SERVER/SIMS_SERVER.pro -o $(MAKEFILE)
sub-SIMS_SERVER: SIMS_SERVER//$(MAKEFILE) FORCE
	cd SIMS_SERVER/ && $(MAKE) -f $(MAKEFILE)
sub-SIMS_SERVER-make_default-ordered: SIMS_SERVER//$(MAKEFILE) FORCE
	cd SIMS_SERVER/ && $(MAKE) -f $(MAKEFILE) 
sub-SIMS_SERVER-make_default: SIMS_SERVER//$(MAKEFILE) FORCE
	cd SIMS_SERVER/ && $(MAKE) -f $(MAKEFILE) 
sub-SIMS_SERVER-make_first-ordered: SIMS_SERVER//$(MAKEFILE) FORCE
	cd SIMS_SERVER/ && $(MAKE) -f $(MAKEFILE) first
sub-SIMS_SERVER-make_first: SIMS_SERVER//$(MAKEFILE) FORCE
	cd SIMS_SERVER/ && $(MAKE) -f $(MAKEFILE) first
sub-SIMS_SERVER-all-ordered: SIMS_SERVER//$(MAKEFILE) FORCE
	cd SIMS_SERVER/ && $(MAKE) -f $(MAKEFILE) all
sub-SIMS_SERVER-all: SIMS_SERVER//$(MAKEFILE) FORCE
	cd SIMS_SERVER/ && $(MAKE) -f $(MAKEFILE) all
sub-SIMS_SERVER-clean-ordered: SIMS_SERVER//$(MAKEFILE) FORCE
	cd SIMS_SERVER/ && $(MAKE) -f $(MAKEFILE) clean
sub-SIMS_SERVER-clean: SIMS_SERVER//$(MAKEFILE) FORCE
	cd SIMS_SERVER/ && $(MAKE) -f $(MAKEFILE) clean
sub-SIMS_SERVER-distclean-ordered: SIMS_SERVER//$(MAKEFILE) FORCE
	cd SIMS_SERVER/ && $(MAKE) -f $(MAKEFILE) distclean
sub-SIMS_SERVER-distclean: SIMS_SERVER//$(MAKEFILE) FORCE
	cd SIMS_SERVER/ && $(MAKE) -f $(MAKEFILE) distclean
sub-SIMS_SERVER-install_subtargets-ordered: SIMS_SERVER//$(MAKEFILE) FORCE
	cd SIMS_SERVER/ && $(MAKE) -f $(MAKEFILE) install
sub-SIMS_SERVER-install_subtargets: SIMS_SERVER//$(MAKEFILE) FORCE
	cd SIMS_SERVER/ && $(MAKE) -f $(MAKEFILE) install
sub-SIMS_SERVER-uninstall_subtargets-ordered: SIMS_SERVER//$(MAKEFILE) FORCE
	cd SIMS_SERVER/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-SIMS_SERVER-uninstall_subtargets: SIMS_SERVER//$(MAKEFILE) FORCE
	cd SIMS_SERVER/ && $(MAKE) -f $(MAKEFILE) uninstall
PanelCommPluginV1//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) PanelCommPluginV1/ || $(MKDIR) PanelCommPluginV1/ 
	cd PanelCommPluginV1/ && $(QMAKE) /home/anton/Desktop/SecureT\ Server/PanelCommPluginV1/PanelCommPluginV1.pro -o $(MAKEFILE)
sub-PanelCommPluginV1-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) PanelCommPluginV1/ || $(MKDIR) PanelCommPluginV1/ 
	cd PanelCommPluginV1/ && $(QMAKE) /home/anton/Desktop/SecureT\ Server/PanelCommPluginV1/PanelCommPluginV1.pro -o $(MAKEFILE)
sub-PanelCommPluginV1: PanelCommPluginV1//$(MAKEFILE) FORCE
	cd PanelCommPluginV1/ && $(MAKE) -f $(MAKEFILE)
sub-PanelCommPluginV1-make_default-ordered: PanelCommPluginV1//$(MAKEFILE) sub-SIMS_SERVER-make_default-ordered  FORCE
	cd PanelCommPluginV1/ && $(MAKE) -f $(MAKEFILE) 
sub-PanelCommPluginV1-make_default: PanelCommPluginV1//$(MAKEFILE) FORCE
	cd PanelCommPluginV1/ && $(MAKE) -f $(MAKEFILE) 
sub-PanelCommPluginV1-make_first-ordered: PanelCommPluginV1//$(MAKEFILE) sub-SIMS_SERVER-make_first-ordered  FORCE
	cd PanelCommPluginV1/ && $(MAKE) -f $(MAKEFILE) first
sub-PanelCommPluginV1-make_first: PanelCommPluginV1//$(MAKEFILE) FORCE
	cd PanelCommPluginV1/ && $(MAKE) -f $(MAKEFILE) first
sub-PanelCommPluginV1-all-ordered: PanelCommPluginV1//$(MAKEFILE) sub-SIMS_SERVER-all-ordered  FORCE
	cd PanelCommPluginV1/ && $(MAKE) -f $(MAKEFILE) all
sub-PanelCommPluginV1-all: PanelCommPluginV1//$(MAKEFILE) FORCE
	cd PanelCommPluginV1/ && $(MAKE) -f $(MAKEFILE) all
sub-PanelCommPluginV1-clean-ordered: PanelCommPluginV1//$(MAKEFILE) sub-SIMS_SERVER-clean-ordered  FORCE
	cd PanelCommPluginV1/ && $(MAKE) -f $(MAKEFILE) clean
sub-PanelCommPluginV1-clean: PanelCommPluginV1//$(MAKEFILE) FORCE
	cd PanelCommPluginV1/ && $(MAKE) -f $(MAKEFILE) clean
sub-PanelCommPluginV1-distclean-ordered: PanelCommPluginV1//$(MAKEFILE) sub-SIMS_SERVER-distclean-ordered  FORCE
	cd PanelCommPluginV1/ && $(MAKE) -f $(MAKEFILE) distclean
sub-PanelCommPluginV1-distclean: PanelCommPluginV1//$(MAKEFILE) FORCE
	cd PanelCommPluginV1/ && $(MAKE) -f $(MAKEFILE) distclean
sub-PanelCommPluginV1-install_subtargets-ordered: PanelCommPluginV1//$(MAKEFILE) sub-SIMS_SERVER-install_subtargets-ordered  FORCE
	cd PanelCommPluginV1/ && $(MAKE) -f $(MAKEFILE) install
sub-PanelCommPluginV1-install_subtargets: PanelCommPluginV1//$(MAKEFILE) FORCE
	cd PanelCommPluginV1/ && $(MAKE) -f $(MAKEFILE) install
sub-PanelCommPluginV1-uninstall_subtargets-ordered: PanelCommPluginV1//$(MAKEFILE) sub-SIMS_SERVER-uninstall_subtargets-ordered  FORCE
	cd PanelCommPluginV1/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-PanelCommPluginV1-uninstall_subtargets: PanelCommPluginV1//$(MAKEFILE) FORCE
	cd PanelCommPluginV1/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: SERVER.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile SERVER.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile SERVER.pro

qmake_all: sub-SIMS_SERVER-qmake_all sub-PanelCommPluginV1-qmake_all FORCE

make_default: sub-SIMS_SERVER-make_default-ordered sub-PanelCommPluginV1-make_default-ordered FORCE
make_first: sub-SIMS_SERVER-make_first-ordered sub-PanelCommPluginV1-make_first-ordered FORCE
all: sub-SIMS_SERVER-all-ordered sub-PanelCommPluginV1-all-ordered FORCE
clean: sub-SIMS_SERVER-clean-ordered sub-PanelCommPluginV1-clean-ordered FORCE
distclean: sub-SIMS_SERVER-distclean-ordered sub-PanelCommPluginV1-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-SIMS_SERVER-install_subtargets-ordered sub-PanelCommPluginV1-install_subtargets-ordered FORCE
uninstall_subtargets: sub-SIMS_SERVER-uninstall_subtargets-ordered sub-PanelCommPluginV1-uninstall_subtargets-ordered FORCE

sub-SIMS_SERVER-check_ordered: SIMS_SERVER/$(MAKEFILE)
	cd SIMS_SERVER/ && $(MAKE) -f $(MAKEFILE) check
sub-PanelCommPluginV1-check_ordered: PanelCommPluginV1/$(MAKEFILE) sub-SIMS_SERVER-check_ordered 
	cd PanelCommPluginV1/ && $(MAKE) -f $(MAKEFILE) check
check: sub-SIMS_SERVER-check_ordered sub-PanelCommPluginV1-check_ordered

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

