#ifndef PANELV1PLUGIN_GLOBAL_H
#define PANELV1PLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PANELV1PLUGIN_LIBRARY)
#  define PANELV1PLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PANELV1PLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PANELV1PLUGIN_GLOBAL_H
