#ifndef PANELCOMMPLUGINV1_GLOBAL_H
#define PANELCOMMPLUGINV1_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PANELCOMMPLUGINV1_LIBRARY)
#  define PANELCOMMPLUGINV1SHARED_EXPORT Q_DECL_EXPORT
#else
#  define PANELCOMMPLUGINV1SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PANELCOMMPLUGINV1_GLOBAL_H
